name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install frontend deps
        run: npm install
        working-directory: frontend
      - name: Check ESLint Errors
        run: npm run lint
        working-directory: frontend
      - name: Build frontend
        run: npm run build
        working-directory: frontend
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install backend deps
        run: npm install
        working-directory: backend
      - name: Run backend tests
        run: npm test
        working-directory: backend
